### PR TITLE
Include dub paths

### PR DESCRIPTION
**Pull request by viniarck**
Hi @landaire and @kraxli, 

This PR addresses issue #3. As long as `dub` is on the user path (so it's not a mandatory dependency for this plugin), it manages to find an unique list of the latest packages (highest string tag). 

Cheers!

### CODE REVIEW

**Comment by viniarck** [comment]
Here's the demo:

msgpack

**Comment by kraxli** [comment]
nice! :-) I pulled your repo and it seems to work great! many thanks!

A small caveat: for long modules, functions, variables, ... there is no space between the names and the types in the pop-up menu

**Comment by viniarck** [comment]
@kraxli, recently I've switched my completion manager com deoplete to ncm2, if you're interested check this out https://github.com/ncm2/ncm2-d

**Comment by kraxli** [comment]
Thanks for letting me know! I have also just switched. Ncm2 is in general a
very refreshing experiance for completion after deoplete - easy to set up
and even ultisnips completion just works without headache  :-)

**Pull request closed without merging**
